# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow gets secrets value
name: AWS example workflow
on:
  push:
  pull_request:
  workflow_dispatch:
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  ReadSecrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          output-credentials: true
      - name: get caller identity 1
        run: |
          aws sts get-caller-identity
      - name: check steps output
        run: |
          echo ${{ steps.creds.outputs.aws-access-key-id }}
          echo ${{ steps.creds.outputs.aws-secret-access-key }}
#      - name:  Read out AWS secrets value
#        run: |
#          export AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }}
#          echo $AWS_ACCESS_KEY_ID
